version: '2'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: yarn run start:dev
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    command: mongod --smallfiles --quiet
    volumes:
      - /mongo/data/db
    ports:
      - 27017:27017
